#version: '3.9'

services:
  credit-risk-api:
    build: .
    container_name: credit-risk-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000  # if you use remote MLflow tracking
    restart: always
